RUN_CODING_HELP = False
RUN_R_ALL = False
RUN_HUGS = False
RUN_DEL_COMMENTS = False
RUN_SUBREDDIT_SNIPER = False

REDDIT_USERNAME = ''
REDDIT_PASS = ''
REDDIT_CLIENT = ''
REDDIT_SECRET = ''

REDDIT_USERNAME_2 = ''
REDDIT_PASS_2 = ''
REDDIT_CLIENT_2 = ''
REDDIT_SECRET_2 = ''

REDDIT_USERNAME_3 = ''
REDDIT_PASS_3 = ''
REDDIT_CLIENT_3 = ''
REDDIT_SECRET_3 = ''

REDDIT_USERNAME_4 = ''
REDDIT_PASS_4 = ''
REDDIT_CLIENT_4 = ''
REDDIT_SECRET_4 = ''

USER_AGENT = ''
USER_AGENT_1 = ''
